# Generated by Django 4.0.4 on 2022-06-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apaterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('amaterno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('celular', models.IntegerField(max_length=999999999, verbose_name='Celular')),
            ],
        ),
    ]
