# Generated by Django 4.0.4 on 2022-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plankton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(max_length=9, verbose_name='Celular'),
        ),
    ]
