# Generated by Django 4.0.4 on 2022-06-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plankton', '0002_alter_usuario_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('precio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Precio')),
                ('foto', models.ImageField(upload_to='users/%Y/%m/%d/', verbose_name='Foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plankton.categoria')),
            ],
        ),
    ]
